### ISSUE TITLE
Code Along errors

### ISSUE THREAD

**Issue by arianaberger** [learn-co-curriculum/rails-activerecord-models-and-rails-readme#11]
It wasn't clear if i should be coding along with this lab. I started to and ran into several errors (rspec rails is not even included in the gemfile, for example). Please make this clear if we should code along and/or update the lesson, thank you!

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials so that this lesson registers as a code along in learn.co, removed the test folder and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
