### ISSUE TITLE
Finished Reading but no "complete ticks"

### ISSUE THREAD

**Issue by malbazaz** [learn-co-curriculum/rails-activerecord-models-and-rails-readme#13]
I finished reading it and clicked on on the finished reading button on the right hand side, and moved to the next lesson. But it's not updating accordingly. It's showing as incomplete. Could you please look into that?

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials so that this lesson correctly registers as a code along and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
