### ISSUE TITLE
Completed but Not updating

### ISSUE THREAD

**Issue by malbazaz** [learn-co-curriculum/rails-activerecord-models-and-rails-readme#14]
I completed the readme but it is not showing that I have completed it.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials so that this lesson correctly registers as a code along and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
